ll.printme()
    # ll.remove_by_value("orange")  # remove orange from linked list
    # ll.printme()
    # ll.remove_by_value("figs")
    # ll.printme()
    # ll.remove_by_value("banana")
    # ll.remove_by_value("mango")
    # ll.remove_by_value("apple")
    # ll.remove_by_value("grapes")
    # ll.printme()